services:
  - type: web
    name: barbershop-sly-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DATABASE_ENGINE
        sync: false
      - key: APP_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: INFO
